### ISSUE TITLE
Config site is freezing when hitting "Test"

### ISSUE THREAD

**Issue by worldworm** [joshp23/YOURLS-FirefoxQuantum#1]
After installing the plugin i went to the configuration site and entered my url and key. When i hit the button test the addon site freezes.
The console outputs "Empty string given to getElementById(). At browser.xml:278:7" (translated from german, could be different in the english ff version.)
Using Firefox 57.0

I tested the plugin already on another computer with firefox 55, there the login process works and shortlinks can be created.

Thanks for your help.

**Comment by joshp23** [comment]
I'm using 57 as well, no issues. Ill take a look.

**Comment by joshp23** [comment]
@worldworm Did you enter in a specific timeout? I found that I had to do that in order to get the plugin to work. Mine didn't freeze, however.

**Comment by worldworm** [comment]
Update:
The url an key got saved nevertheless, after reinstalling the plugin (without removing before) the shortening function is working now. But hiting test again and the same thing explained above will happen.

As a timout i tried different values between 1 and 10000

**Comment by joshp23** [comment]
That's odd. Glad it worked out. I'll try to reproduce this error.

**Comment by worldworm** [comment]
Thanks

does the context right click function works for you?
does the provide keyword function works?
Or is my firefox broken and need a new installation?
Should i open a seperat issue for these above? Or is it known.

I will delete this after your answer so that iam not spamming this issue with another topic :)

**Comment by joshp23** [comment]
Note that the right click, or "context" function does not work in this release, nor has the provide keyword feature been implemented.

**Comment by worldworm** [comment]
ok, got it :)

**Comment by joshp23** [comment]
Original code updated! Please use that, instead.
